name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
      - run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
      - run: bin/rails db:setup
      - run: bin/rails test
      - run: bundle exec rubocop
      - run: bundle exec brakeman --no-exit-on-warn

